name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: apt update && apt install libpthread-stubs0-dev libc6
    - name: make test
      run: make test
    - name: run tests
      run: ./test
